# Generated by Django 3.0.3 on 2020-02-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('channel', models.TextField()),
                ('country', models.CharField(max_length=2)),
                ('os', models.TextField()),
                ('impressions', models.PositiveIntegerField()),
                ('clicks', models.PositiveIntegerField()),
                ('installs', models.PositiveIntegerField()),
                ('spend', models.FloatField()),
                ('revenue', models.FloatField()),
            ],
        ),
    ]
