# Generated by Django 3.0.3 on 2020-02-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataManipulator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerformanceMetric',
            new_name='PerformanceMetricItem',
        ),
    ]
